'use strict';
const path=require('path');global.window=global;
const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
let seed=0xC0FFEE;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;function assert(x,m){if(!x)throw new Error(m);}
function score(c,b,i){let hits=Math.max(c.hits||1,c.conditionalHits&&Object.values(b.enemy.status).some(x=>x>0)?c.conditionalHits:0,c.lowHpHits&&b.player.hp<=b.player.maxHp/2?c.lowHpHits:0);let dmg=(c.lowHpDamage&&b.player.hp<=b.player.maxHp/2?c.lowHpDamage:c.damage||0)*hits;let block=(c.lowHpBlock&&b.player.hp<=b.player.maxHp/2?c.lowHpBlock:c.block||0);let st=(c.status?.amount||0)*2+(c.perHitStatus?.amount||0)*hits*1.8+(c.statuses?.reduce((a,x)=>a+x.amount,0)||0)*1.5;let v=dmg+block*1.15+st-(c.selfDamage||0)*1.7;if(b.player.hp<25)v+=block*1.2-(c.selfDamage||0)*3;if(c.consumeStatus||c.consumeStatuses)v+=10;const center=Math.floor((b.prompt.length-1)/2);if(BL.Store.state.character==='standard'&&i===center)v*=1.55;if(b.isBoss&&i===center&&b.player.hp<25)v-=10;return v;}
const builds=[
{name:'combo',character:'combo',deck:['toxic_cascade','swift_toxin','toxic_barrage','searing_flurry','follow_up','plague_blade','blight_wall','guard_barrage','dual_detonation','rapid_guard'],relics:['multi_core','impact_mesh','execution_lens']},
{name:'fort',character:'tank',deck:['shield_ram','fortress_ram','retaliation_engine','counter_stance','counter_cut','brace_focus','deep_cycle_guard','bastion_recycle','blight_wall','patient_execution'],relics:['counter_core','steadfast_frame','bastion_memory']},
{name:'discard',character:'standard',deck:['discard_salvo','scrap_bastion','latent_charge','discard_counter','shard_shot','emergency_cache','volatile_ash','toxin_residue','scavenger_cut','abandoned_guard'],relics:['offcut_engine','discard_furnace','discard_memory']}
];
let viable=0;for(const cfg of builds){let wins=0;for(let t=0;t<120;t++){BL.Store.state=BL.Store.defaultState();BL.Store.state.character=cfg.character;BL.Store.state.deck=[...cfg.deck];BL.Store.state.relics=[...cfg.relics];let result=null;BL.Battle.onEnd=r=>result=r;BL.Battle.create(true);let step=0;while(BL.Battle.current&&step<60){const b=BL.Battle.current;let bi=0,bv=-1e9;b.prompt.forEach((x,i)=>{const v=score(D.CARDS[x.cardId],b,i);if(v>bv){bv=v;bi=i;}});BL.Battle.play(bi);step++;}if(BL.Battle.current)BL.Battle.retire();if(result?.win)wins++;}const rate=wins/120;console.log(`boss balance ${cfg.name}: ${(rate*100).toFixed(1)}%`);if(rate>=.15)viable++;}
assert(viable>=3,`第1ボスに対して現実的な突破率を持つ検証ビルドが不足: ${viable}/3`);
console.log('PASS boss_balance.test.js');
