'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/<script src="([^"?]+)/g)){const f=m[1];if(f.includes('/ui/')||f.endsWith('app.js'))continue;require(path.join(root,f));}const BL=BuildLab,D=BL.Data;
function unlock(s){for(const [src,dst] of Object.entries({CARDS:'unlockedCards',RELICS:'unlockedRelics',CHARACTERS:'unlockedCharacters',PROTOCOLS:'unlockedProtocols',TUNINGS:'unlockedTunings',CARD_CONVERSIONS:'unlockedConversions',DOCTRINES:'unlockedDoctrines'}))for(const id of Object.keys(D[src]||{}))s[dst][id]=true;s.unlockedSystems={prompt_control:true,advanced_enemy_parameters:true,card_tuning:true,card_link:true,card_conversion:true,deck_doctrine:true};}
function score(x,b){const c=D.CARDS[x.cardId];let v=(c.damage||0)*(c.hits||1)*1.2+(c.block||0)*1.5+(c.status?.amount||0)*4;const pair=BL.Store.state.cardLink;if(pair?.a&&pair?.b){if(!b.lastUsed&&(x.cardId===pair.a||x.cardId===pair.b))v*=2.5;if(b.lastUsed){const want=b.lastUsed.cardId===pair.a?pair.b:b.lastUsed.cardId===pair.b?pair.a:null;if(want===x.cardId)v*=4.5;}}if((c.block||c.kind==='block'||c.kind==='hybrid')&&b.player.hp<35)v*=2;return v;}
function run(cfg,t){let seed=0xC0554+t*7919;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const s=BL.Store.defaultState();unlock(s);Object.assign(s,cfg);BL.Store.state=s;let result=null;BL.Battle.onEnd=r=>result=r;BL.Battle.create('boss4');let step=0;while(BL.Battle.current&&step<60){const b=BL.Battle.current;let bi=0,bv=-1e9;b.prompt.forEach((x,i)=>{const v=score(x,b);if(v>bv){bv=v;bi=i;}});BL.Battle.play(bi);step++;}if(BL.Battle.current)BL.Battle.retire();return !!result?.win;}
const prior={character:'relay',deck:['link_strike','link_strike','link_guard','link_guard','link_barrage','link_poison','relay_blade','relay_wall','linked_bastion','tuned_link'],relics:['link_core','relay_buffer','pair_memory'],protocol:'link_guardian',cardLink:{a:'link_strike',b:'link_guard'},cardTunings:{link_strike:'relay',link_guard:'guard'},cardConversions:{relay_blade:'split',relay_wall:'counter_role'},doctrine:null};
const integrated={character:'architect',deck:['link_strike','link_strike','link_guard','link_guard','linked_bastion','linked_blood','linked_residue','linked_cycle','tuned_link','link_recovery'],relics:['doctrine_core','doctrine_guard','doctrine_link'],protocol:'doctrine_bridge',doctrine:'hybrid',cardLink:{a:'link_strike',b:'link_guard'},cardTunings:{link_strike:'relay',link_guard:'guard'},cardConversions:{linked_blood:'split',linked_residue:'cycle_role'}};
let oldWins=0,newWins=0,N=60;for(let i=0;i<N;i++){if(run(prior,i))oldWins++;if(run(integrated,i))newWins++;}
console.log(`boss4 progression: pre-doctrine ${(oldWins/N*100).toFixed(1)}% / doctrine-integrated ${(newWins/N*100).toFixed(1)}%`);
assert(oldWins/N<=.25,'第3章までの連結力押しで第4ボスを安定突破できてしまう');assert(newWins/N>=.70,'構築規格＋統合運用でも第4ボス突破率が不足');
console.log('PASS boss4_balance.test.js');
