'use strict';
const path=require('path');global.window=global;
const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;const assert=(x,m)=>{if(!x)throw new Error(m);};
BL.Store.state=BL.Store.defaultState();
BL.Store.state.deck=Array(10).fill('double_strike');
BL.Store.state.defeatedTraits={giant:true,berserk:true,armored:true,fast:true};
let result=null;BL.Battle.onEnd=r=>result=r;
const start=BL.Battle.create(true);assert(!start.error,'boss integration start failed');
BL.Battle.current.enemy.hp=1;
BL.Battle.play(0);
assert(result?.win,'ボス撃破結果がwinになっていません');
assert(BL.Battle.current===null,'ボス撃破後も戦闘が残っています');
assert(BL.Store.state.bossDefeated,'bossDefeatedが保存されていません');
assert(BL.Store.state.claimedUnlocks.boss_clear,'boss_clearが戦闘終了経路で達成されていません');
assert(BL.Store.state.unlockedSystems.prompt_control,'提示操作システムが戦闘終了経路で解放されていません');
for(const id of D.BOSS1_REWARD_CARD_IDS)assert(BL.Store.state.unlockedCards[id],`カード報酬が未解放: ${id}`);
for(const id of D.BOSS1_REWARD_RELIC_IDS)assert(BL.Store.state.unlockedRelics[id],`遺物報酬が未解放: ${id}`);
assert(BL.Store.state.unlockedSystems.advanced_enemy_parameters,'高度敵パラメータが戦闘終了経路で解放されていません');
for(const id of ['center_drive','wide_scan','narrow_scan'])assert(BL.Store.state.unlockedProtocols[id],`プロトコル報酬が未解放: ${id}`);
assert(result.newUnlocks.includes('提示操作システム'),'結果画面用newUnlocksに提示操作システムがありません');
const saved=JSON.parse(mem[BL.Store.KEY]);assert(saved.unlockedSystems.prompt_control,'localStorage保存後に提示操作システムがありません');
console.log('PASS boss_reward_integration.test.js');
