'use strict';
const path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};let seed=0xC0553;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/data/expansion17.js','js/data/expansion18.js','js/data/expansion19.js','js/data/runes.js','js/data/arcana.js','js/data/expansion20.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/data/unlocks17.js','js/data/unlocks18.js','js/data/unlocks19.js','js/data/unlocks20.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;const assert=(x,m)=>{if(!x)throw new Error(m);};
function score(c,b,i){let hits=Math.max(c.hits||1,c.conditionalHits&&Object.values(b.enemy.status).some(x=>x>0)?c.conditionalHits:0,c.lowHpHits&&b.player.hp<=b.player.maxHp/2?c.lowHpHits:0);const center=Math.floor((b.prompt.length-1)/2),pos=i<center?'left':i===center?'center':'right';if(c.hitsIfPosition?.position===pos)hits=Math.max(hits,c.hitsIfPosition.value);let dmg=(c.lowHpDamage&&b.player.hp<=b.player.maxHp/2?c.lowHpDamage:c.damage||0)*hits;if(c.damageIfPosition?.position===pos)dmg=c.damageIfPosition.value*hits;if(c.damageIfEnemyRegenMin&&b.enemy.regen>=c.damageIfEnemyRegenMin.min)dmg=c.damageIfEnemyRegenMin.value*hits;if(c.damageIfEnemyResistMin&&b.enemy.resist>=c.damageIfEnemyResistMin.min)dmg=c.damageIfEnemyResistMin.value*hits;let block=(c.lowHpBlock&&b.player.hp<=b.player.maxHp/2?c.lowHpBlock:c.block||0);if(c.blockIfPosition?.position===pos)block=c.blockIfPosition.value;if(c.blockIfEnemyRegenMin&&b.enemy.regen>=c.blockIfEnemyRegenMin.min)block=c.blockIfEnemyRegenMin.value;if(c.blockIfEnemyResistMin&&b.enemy.resist>=c.blockIfEnemyResistMin.min)block=c.blockIfEnemyResistMin.value;let st=(c.status?.amount||0)*2+(c.perHitStatus?.amount||0)*hits*1.7;let v=dmg+block*1.3+st-(c.selfDamage||0)*1.8;if(b.player.hp<25)v+=block*1.5-(c.selfDamage||0)*3;if(c.consumeStatus||c.consumeStatuses)v+=10;if(BL.Store.state.character==='standard'&&i===center)v*=1.5;if(b.lastChoicePosition===pos)v-=10;return v;}
const builds=[
{name:'position',character:'standard',deck:['center_burst','center_guard','left_sweep','right_charge','center_counter','left_guard','right_poison','position_cycle','reserve_blade','reserve_guard'],relics:['center_compass','position_prism','reserve_amplifier'],protocol:'center_drive'},
{name:'adaptive',character:'combo',deck:['regen_sever','cautery_wall','sterile_breaker','purity_rain','adaptive_guard','adaptive_edge','resistance_saw','scorched_wound','relentless_cut','sterile_wall'],relics:['regen_clamp','null_lens','convergence_core'],protocol:'adaptive_build'},
{name:'tuned',character:'tank',deck:['tuned_edge','tuned_guard','tuned_barrage','tuned_toxin','overload_bastion','recycle_lance','center_guard','center_burst','adaptive_guard','adaptive_edge'],relics:['tuning_core','adaptive_lens','second_observer'],protocol:'tuned_overdrive',tunings:{tuned_edge:'overload',tuned_guard:'recycle'}}
];
let viable=0;for(const cfg of builds){let wins=0;for(let t=0;t<100;t++){BL.Store.state=BL.Store.defaultState();Object.assign(BL.Store.state,{bossDefeated:true,character:cfg.character,deck:[...cfg.deck],relics:[...cfg.relics],protocol:cfg.protocol||null,cardTunings:cfg.tunings||{}});Object.keys(D.CHARACTERS).forEach(id=>BL.Store.state.unlockedCharacters[id]=true);cfg.relics.forEach(id=>BL.Store.state.unlockedRelics[id]=true);if(cfg.protocol)BL.Store.state.unlockedProtocols[cfg.protocol]=true;BL.Store.state.unlockedSystems.card_tuning=true;let result=null;BL.Battle.onEnd=r=>result=r;BL.Battle.create('boss4');let step=0;while(BL.Battle.current&&step<60){const b=BL.Battle.current;let bi=0,bv=-1e9;b.prompt.forEach((x,i)=>{const v=score(D.CARDS[x.cardId],b,i);if(v>bv){bv=v;bi=i;}});BL.Battle.play(bi);step++;}if(BL.Battle.current)BL.Battle.retire();if(result?.win)wins++;}const rate=wins/100;console.log(`boss4 balance ${cfg.name}: ${(rate*100).toFixed(1)}%`);if(rate>=.15)viable++;}
assert(viable>=3,`第4ボスに対して現実的な突破率を持つ検証ビルドが不足: ${viable}/3`);console.log('PASS boss4_balance.test.js');
