'use strict';const fs=require('fs'),path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};const root=path.resolve(__dirname,'..'),html=fs.readFileSync(root+'/index.html','utf8');for(const m of html.matchAll(/<script src="([^"?]+)/g)){const f=m[1];if(f.includes('/ui/')||f.endsWith('app.js'))continue;require(path.join(root,f));}const BL=BuildLab,D=BL.Data;
function unlockAll(s){for(const [src,dst] of Object.entries({CARDS:'unlockedCards',RELICS:'unlockedRelics',CHARACTERS:'unlockedCharacters',PROTOCOLS:'unlockedProtocols',TUNINGS:'unlockedTunings',CARD_CONVERSIONS:'unlockedConversions',RUNES:'unlockedRunes',ARCANA:'unlockedArcana',DOCTRINES:'unlockedDoctrines',LINK_MODES:'unlockedLinkModes'}))for(const id of Object.keys(D[src]||{}))s[dst][id]=true;s.unlockedSystems={advanced_enemy_parameters:true,prompt_control:true,card_link:true,card_conversion:true,deck_doctrine:true,rune:true,arcana:true,card_tuning:true,character_style:true};}
function score(id,b,i){const c=D.CARDS[id];let hits=Math.max(c.hits||1,c.conditionalHits&&Object.values(b.enemy.status).some(x=>x>0)?c.conditionalHits:0,c.lowHpHits&&b.player.hp<=b.player.maxHp/2?c.lowHpHits:0,c.hitsIfLinkedCombo&&b.lastUsed?c.hitsIfLinkedCombo:0);let dmg=(c.damage||0)*hits,block=c.block||0;const center=Math.floor((b.prompt.length-1)/2),pos=i<center?'left':i===center?'center':'right';if(c.damageIfPosition?.position===pos)dmg=Math.max(dmg,c.damageIfPosition.value*hits);if(c.blockIfPosition?.position===pos)block=Math.max(block,c.blockIfPosition.value);if(c.damageIfEnemyRegenMin&&b.enemy.regen>=c.damageIfEnemyRegenMin.min)dmg=Math.max(dmg,c.damageIfEnemyRegenMin.value*hits);if(c.damageIfEnemyResistMin&&b.enemy.resist>=c.damageIfEnemyResistMin.min)dmg=Math.max(dmg,c.damageIfEnemyResistMin.value*hits);if(c.blockIfEnemyRegenMin&&b.enemy.regen>=c.blockIfEnemyRegenMin.min)block=Math.max(block,c.blockIfEnemyRegenMin.value);if(c.blockIfEnemyResistMin&&b.enemy.resist>=c.blockIfEnemyResistMin.min)block=Math.max(block,c.blockIfEnemyResistMin.value);let v=dmg*1.1+block*1.4+(c.status?.amount||0)*3+(c.perHitStatus?.amount||0)*hits*2-(c.selfDamage||0)*2;if(b.player.hp<25)v+=block*1.6; const pair=BL.Store.state.cardLink;if(pair?.a&&pair?.b&&b.lastUsed){const want=b.lastUsed.cardId===pair.a?pair.b:b.lastUsed.cardId===pair.b?pair.a:null;if(want===id)v*=3.5;}if(BL.Store.state.character==='standard'&&pos==='center')v*=1.3;if(b.lastChoicePosition===pos&&b.bossId==='boss2')v*=.65;return v;}
const builds={
 prev1:{character:'combo',deck:['double_strike','needle_rain','follow_up','accelerated_slash','triple_cut','puncture_chain','patient_guard','wall','parry','counter_stance'],relics:['multiblade','chain_reactor','perfect_wall'],protocol:'multihit_accelerator'},
 boss2:{character:'standard',deck:['center_burst','center_guard','left_sweep','right_charge','center_counter','left_guard','right_poison','position_cycle','reserve_blade','reserve_guard'],relics:['center_compass','position_prism','reserve_amplifier'],protocol:'center_drive',tunings:{center_burst:'focus',center_guard:'focus'}},
 boss3:{character:'relay',deck:['link_strike','link_guard','link_barrage','link_poison','relay_blade','relay_wall','linked_bastion','linked_cycle','tuned_link','link_recovery'],relics:['link_core','relay_buffer','linked_tuner'],protocol:'tuned_relay',link:{a:'link_strike',b:'link_guard'},tunings:{link_strike:'relay',link_guard:'relay'},conversions:{}},
 boss4:{character:'architect',deck:['link_strike','link_guard','tuned_link','linked_bastion','relay_blade','relay_wall','center_burst','center_guard','adaptive_edge','adaptive_guard'],relics:['v20_total_core','v20_rune_linker','v20_arcana_link'],protocol:'v20_p_total',link:{a:'link_strike',b:'link_guard'},tunings:{link_strike:'relay',link_guard:'relay',tuned_link:'v20_integrated'},doctrine:'hybrid',runes:{link_strike:'rune_force',link_guard:'rune_ward',tuned_link:'rune_barrage'},arcana:{id:'arcana_strength',orientation:'upright'}}
};
// add conversions to boss4 where valid
for(const id of ['link_strike','link_guard','tuned_link']){const cv=Object.keys(D.CARD_CONVERSIONS||{}).find(x=>D.canApplyConversion?.(id,x));if(cv)builds.boss4.conversions=Object.assign(builds.boss4.conversions||{},{[id]:cv});}
function rate(mode,cfg,n=80){let wins=0;for(let t=0;t<n;t++){let seed=(0x660000+t*3571+mode.charCodeAt(4))>>>0;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const s=BL.Store.defaultState();unlockAll(s);s.character=cfg.character;s.deck=[...cfg.deck];s.relics=[...cfg.relics];s.protocol=cfg.protocol||null;s.cardTunings={...(cfg.tunings||{})};s.cardConversions={...(cfg.conversions||{})};s.cardLink=cfg.link||{a:null,b:null};s.linkMode='reciprocal';s.doctrine=cfg.doctrine||null;s.cardRunes={...(cfg.runes||{})};s.arcana=cfg.arcana||{id:null,orientation:'upright'};BL.Store.state=s;let result=null;BL.Battle.onEnd=r=>result=r;const cr=BL.Battle.create(mode);if(cr.error){console.log('create err',mode,cr.error);return -1;}let steps=0;while(BL.Battle.current&&steps<80){const b=BL.Battle.current;let bi=0,bv=-1e9;b.prompt.forEach((x,i)=>{const v=score(x.cardId,b,i);if(v>bv){bv=v;bi=i;}});BL.Battle.play(bi);steps++;}if(BL.Battle.current)BL.Battle.retire();if(result?.win)wins++;}return wins/n;}
const rows=[];for(const [mode,prev,current] of [['boss2','prev1','boss2'],['boss3','boss2','boss3'],['boss4','boss3','boss4']]){const oldRate=rate(mode,builds[prev]),newRate=rate(mode,builds[current]);rows.push({mode,oldRate,newRate});if(newRate<.25)throw new Error(`${mode}: 現章システム構成の突破率が低すぎる ${(newRate*100).toFixed(1)}%`);if(newRate-oldRate<.20)throw new Error(`${mode}: 前章構成との差が不足 old ${(oldRate*100).toFixed(1)}% / current ${(newRate*100).toFixed(1)}%`);if(oldRate>.15)throw new Error(`${mode}: 前章要素だけで突破しやすすぎる ${(oldRate*100).toFixed(1)}%`);console.log(`${mode}: previous ${(oldRate*100).toFixed(1)}% -> chapter ${(newRate*100).toFixed(1)}%`);}console.log('PASS chapter_boss_progression.test.js');
