'use strict';
const fs=require('fs'),path=require('path');global.window=global;require(path.resolve(__dirname,'../js/data/gameData.js'));require(path.resolve(__dirname,'../js/data/protocols.js'));require(path.resolve(__dirname,'../js/data/tunings.js'));require(path.resolve(__dirname,'../js/data/conversions.js'));require(path.resolve(__dirname,'../js/data/chapter3.js'));require(path.resolve(__dirname,'../js/data/expansion08.js'));require(path.resolve(__dirname,'../js/data/expansion09.js'));require(path.resolve(__dirname,'../js/data/doctrines.js'));require(path.resolve(__dirname,'../js/data/characterStyles.js'));require(path.resolve(__dirname,'../js/data/expansion10.js'));require(path.resolve(__dirname,'../js/data/expansion11.js'));require(path.resolve(__dirname,'../js/data/expansion12.js'));require(path.resolve(__dirname,'../js/data/enemyBehaviors.js'));require(path.resolve(__dirname,'../js/data/expansion13.js'));require(path.resolve(__dirname,'../js/data/expansion14.js'));require(path.resolve(__dirname,'../js/data/expansion17.js'));require(path.resolve(__dirname,'../js/data/expansion18.js'));
const D=global.BuildLab.Data,battle=fs.readFileSync(path.resolve(__dirname,'../js/core/battle.js'),'utf8');
const meta=new Set(['name','tags','desc','kind']);
const keys=[...new Set(Object.values(D.CARDS).flatMap(c=>Object.keys(c)).filter(k=>!meta.has(k)))];
const missing=keys.filter(k=>!battle.includes(k));if(missing.length)throw new Error('戦闘コードに未接続のカード効果プロパティがあります: '+missing.join(', '));
const uiRelics=new Set([]);const missingRelics=Object.keys(D.RELICS).filter(id=>!battle.includes(`'${id}'`)&&!uiRelics.has(id)&&!D.V13_RELIC_RULES?.[id]&&!D.V14_RELIC_RULES?.[id]);if(missingRelics.length)throw new Error('戦闘コードに未接続の遺物があります: '+missingRelics.join(', '));
const missingProtocols=Object.keys(D.PROTOCOLS).filter(id=>!battle.includes(`'${id}'`)&&!D.V13_PROTOCOL_RULES?.[id]&&!D.V14_PROTOCOL_RULES?.[id]);if(missingProtocols.length)throw new Error('戦闘コードに未接続の強化プロトコルがあります: '+missingProtocols.join(', '));
const missingTunings=Object.values(D.TUNINGS).map(t=>t.effect).filter(e=>!battle.includes(`'${e}'`));if(missingTunings.length)throw new Error('戦闘コードに未接続のカード調律があります: '+missingTunings.join(', '));
const missingConversions=Object.values(D.CARD_CONVERSIONS||{}).map(x=>x.effect).filter(e=>!battle.includes(`'${e}'`));if(missingConversions.length)throw new Error('戦闘コードに未接続の役割変換があります: '+missingConversions.join(', '));
const missingStyles=Object.keys(D.CHARACTER_STYLES||{}).filter(id=>!battle.includes(`'${id}'`));if(missingStyles.length)throw new Error('戦闘コードに未接続のキャラクタースタイルがあります: '+missingStyles.join(', '));

const behaviorRuleKeys=[...new Set(Object.values(D.ENEMY_BEHAVIORS||{}).flatMap(x=>Object.keys(x.rules||{})))];const missingBehaviorRules=behaviorRuleKeys.filter(k=>!battle.includes(k));if(missingBehaviorRules.length)throw new Error('複合挙動ルールが戦闘コードへ未接続です: '+missingBehaviorRules.join(', '));
const doctrineMarkers=['duplicate','hybrid','spectrum','compact','expanded','singleton'];for(const id of Object.keys(D.DOCTRINES||{})){if(!doctrineMarkers.includes(id))throw new Error('未知の構築規格: '+id);} 
console.log(`PASS effect_coverage.test.js (${keys.length} card properties / ${Object.keys(D.RELICS).length} relics / ${Object.keys(D.PROTOCOLS).length} protocols / ${Object.keys(D.TUNINGS).length} tunings / ${Object.keys(D.CHARACTER_STYLES||{}).length} styles / ${Object.keys(D.CARD_CONVERSIONS||{}).length} conversions / ${Object.keys(D.ENEMY_BEHAVIORS||{}).length} behaviors)`);
