'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const data=fs.readFileSync(path.join(root,'js/data/gameData.js'),'utf8');
const battle=fs.readFileSync(path.join(root,'js/core/battle.js'),'utf8');
for(const token of ['blockIfRecovered','blockIfHpRecovery','blockIfLastHpDirectionUp','fixedCounterIfHpRecovery','recoverBloodDiscard','buffNextSelfDamageAfterHeal','buffNextSelfDamage'])assert(data.includes(token)||battle.includes(token),`missing ${token}`);
for(const id of ['scarlet_bulwark','blood_armor','recovery_guard','pain_reflex','red_cycle'])assert(data.includes(id+':'),`missing ${id}`);
assert(data.includes("effect:'recoverBloodDiscard'"));
assert(battle.includes('nextSelfDamageBuff'));
assert(!data.includes("pain_reflex:{name:'痛覚反射',tags:['自傷','耐久'],desc:'HP2を失い、防御8。次に使うカードの効果+25%。"));
console.log('PASS history40_blood_engine.test.js');
