'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const battle=fs.readFileSync(path.join(root,'js/core/battle.js'),'utf8');
const ch3=fs.readFileSync(path.join(root,'js/data/chapter3.js'),'utf8');
assert(battle.includes('linkHistory:{pairStreak:0,directionAlternations:0,lastDirection:null}'),'連結履歴が初期化される');
assert(battle.includes('directionAlternations'),'A→B/B→Aの方向交替を記録する');
assert(battle.includes('Math.min(.08'),'接続熟練の上限が8%に固定される');
assert(battle.includes('Math.min(.06'),'方向交替の上限が6%に固定される');
assert(ch3.includes("damageIfLinkedCombo:14"),'連結刃を巨大条件値ではなく運用型へ正常化');
assert(ch3.includes("blockIfLinkedCombo:13"),'連結防壁を正常化');
assert(ch3.includes("hitsIfLinkedCombo:4"),'連結連射のhit膨張を抑制');
assert(ch3.includes("statusIfLinkedCombo:5"),'連結毒を継続投与部品へ変更');
console.log('PASS link45_mastery.test.js');
