'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.join(__dirname,'..');
const ctx={window:{},console,structuredClone:global.structuredClone};ctx.window.window=ctx.window;vm.createContext(ctx);
for(const f of ['js/data/gameData.js','js/core/utils.js','js/core/battle.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const D=ctx.window.BuildLab.Data,src=fs.readFileSync(path.join(root,'js/core/battle.js'),'utf8');
for(const id of ['role_recorder','record_replay','route_marker','returning_probe','rough_edge','polished_edge','void_cocoon','hatched_shell','recall_beacon'])assert(D.CARDS[id],id);
assert.equal(D.CARDS.rough_edge.damage,6);assert.equal(D.CARDS.polished_edge.damage,10);
assert.deepEqual(JSON.parse(JSON.stringify(D.CARDS.rough_edge.transformAfterEvent)),{type:'notChosen',count:2,into:'polished_edge'});
assert.equal(D.CARDS.void_cocoon.transformOnReturn,'hatched_shell');
assert(!D.POST_BOSS_CARD_IDS.includes('polished_edge'),'transformed face must not be directly deckable');
assert(!D.POST_BOSS_CARD_IDS.includes('hatched_shell'),'return-only face must not be directly deckable');
for(const token of ["emitEvent('recorded'","emitEvent('recordReplayed'","emitEvent('reserved'","emitEvent('reservationArrived'","emitEvent('returnedFromVanish'","type:'transformed'"])assert(src.includes(token),token);
assert(src.includes("transformedCardId||x.cardId"));
assert(src.includes("reserveSelfAfterUse"));
console.log('mechanics51_record_reserve_transform_return.test.js: PASS');
