'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/<script src="([^"?]+)/g)){const f=m[1];if(f.includes('/ui/')||f.endsWith('app.js'))continue;require(path.join(root,f));}const BL=BuildLab,D=BL.Data;
function unlock(s){for(const [src,dst] of Object.entries({CARDS:'unlockedCards',RELICS:'unlockedRelics',CHARACTERS:'unlockedCharacters',PROTOCOLS:'unlockedProtocols',TUNINGS:'unlockedTunings'}))for(const id of Object.keys(D[src]||{}))s[dst][id]=true;s.unlockedSystems={prompt_control:true,advanced_enemy_parameters:true,card_tuning:true};}
function score(x,b,i){const c=D.CARDS[x.cardId];const center=Math.floor((b.prompt.length-1)/2),pos=i<center?'left':i===center?'center':'right';let v=(c.damage||0)*(c.hits||1)*1.2+(c.block||0)*1.5+(c.status?.amount||0)*4;if(c.damageIfPosition?.position===pos)v+=c.damageIfPosition.value*1.3;if(c.blockIfPosition?.position===pos)v+=c.blockIfPosition.value*1.5;if((c.block||c.kind==='block'||c.kind==='hybrid')&&b.player.hp<30)v*=2;return v;}
function run(cfg,t){let seed=0xB0362+t*7919;Math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const s=BL.Store.defaultState();unlock(s);Object.assign(s,cfg);BL.Store.state=s;let result=null;BL.Battle.onEnd=r=>result=r;BL.Battle.create('boss2');let step=0;while(BL.Battle.current&&step<60){const b=BL.Battle.current;let bi=0,bv=-1e9;b.prompt.forEach((x,i)=>{const v=score(x,b,i);if(v>bv){bv=v;bi=i;}});BL.Battle.play(bi);step++;}if(BL.Battle.current)BL.Battle.retire();return !!result?.win;}
const chapter1={character:'combo',deck:['sixfold_cut','sixfold_cut','combo_accel','combo_accel','drill_guard','drill_guard','chain_shatter','chain_shatter','pain_barrage','pain_barrage'],relics:['multihit_lens','overrotation','tempo_spool'],protocol:'multihit_accelerator',cardTunings:{}};
const chapter2={character:'standard',deck:['center_burst','center_guard','left_sweep','right_charge','center_counter','left_guard','right_poison','position_cycle','reserve_blade','reserve_guard'],relics:['center_compass','position_prism','reserve_amplifier'],protocol:'center_drive',cardTunings:{center_burst:'focus',reserve_guard:'reserve'}};
let oldWins=0,newWins=0,N=60;for(let i=0;i<N;i++){if(run(chapter1,i))oldWins++;if(run(chapter2,i))newWins++;}
console.log(`boss2 progression: chapter1-only ${(oldWins/N*100).toFixed(1)}% / chapter2 prompt+tuning ${(newWins/N*100).toFixed(1)}%`);
assert(oldWins/N<=.20,'第1章だけの多段火力で第2ボスを安定突破できてしまう');assert(newWins/N>=.55,'第2章の提示操作・調律を理解しても第2ボス突破率が不足');
console.log('PASS progression36_boss2_gate.test.js');
