'use strict';
const fs=require('fs'),path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/data/expansion17.js','js/data/expansion18.js','js/data/expansion19.js','js/data/runes.js','js/data/arcana.js','js/data/expansion20.js','js/data/balance22.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/data/unlocks17.js','js/data/unlocks18.js','js/data/unlocks19.js','js/data/unlocks20.js','js/core/state.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data,assert=(x,m)=>{if(!x)throw new Error(m)};
let s=BL.Store.defaultState();s.unlockedDoctrines.compact=true;s.doctrine='compact';s.deck=Array(8).fill(D.DEFAULT_DECK[0]);s.relics=['selection_lens'];s.protocol='fortify_calibration';s.unlockedProtocols.fortify_calibration=true;s.cardTunings={[D.DEFAULT_DECK[0]]:'overload'};s.cardConversions={[D.DEFAULT_DECK[1]]:'split'};s.unlockedConversions.split=true;s.cardLink={a:D.DEFAULT_DECK[0],b:D.DEFAULT_DECK[1]};s.linkMode='forward';s.unlockedLinkModes.forward=true;s.character='combo';s.characterStyles={combo:'combo_cascade'};s.unlockedCharacterStyles.combo_cascade=true;s.enemy={hp:9,atk:7,def:5,spd:3,regen:4,resist:50,traits:{giant:true}};s.claimedUnlocks.keep_me=true;s.stats={wins:12,losses:4,bossWins:2};BL.Store.state=s;
BL.Store.resetDeck();assert(BL.Store.state.deck.length===8,'compact deck reset size');assert(BL.Store.state.doctrine==='compact','deck reset should keep doctrine');
BL.Store.state.cardTunings={[D.DEFAULT_DECK[0]]:'overload'};BL.Store.state.cardConversions={[D.DEFAULT_DECK[1]]:'split'};BL.Store.state.cardRunes={[D.DEFAULT_DECK[0]]:'dummy_rune'};const unlockSnapshot=JSON.stringify(BL.Store.state.claimedUnlocks);BL.Store.clearDeck();assert(BL.Store.state.deck.length===0,'deck clear should remove every card');assert(BL.Store.state.cardTunings[D.DEFAULT_DECK[0]]==='overload','deck clear erased tuning');assert(BL.Store.state.cardConversions[D.DEFAULT_DECK[1]]==='split','deck clear erased conversion');assert(BL.Store.state.cardRunes[D.DEFAULT_DECK[0]]==='dummy_rune','deck clear erased rune assignment');assert(JSON.stringify(BL.Store.state.claimedUnlocks)===unlockSnapshot,'deck clear erased progress');
BL.Store.resetRelics();assert(BL.Store.state.relics.length===0,'relic reset');BL.Store.resetProtocol();assert(BL.Store.state.protocol===null,'protocol reset');BL.Store.resetTunings();assert(Object.keys(BL.Store.state.cardTunings).length===0,'tuning reset');BL.Store.resetConversions();assert(Object.keys(BL.Store.state.cardConversions).length===0,'conversion reset');BL.Store.resetLinks();assert(!BL.Store.state.cardLink.a&&!BL.Store.state.cardLink.b&&BL.Store.state.linkMode==='reciprocal','link reset');BL.Store.resetCurrentStyle();assert(!BL.Store.state.characterStyles.combo,'style reset');BL.Store.state.enemy={hp:9,atk:7,def:5,spd:3,regen:4,resist:50,traits:{giant:true,berserk:true}};BL.Store.resetEnemyTraits();assert(BL.Store.state.enemy.hp===9&&BL.Store.state.enemy.atk===7&&BL.Store.state.enemy.regen===4,'trait clear changed enemy stats');assert(Object.keys(BL.Store.state.enemy.traits).length===0,'trait clear failed');BL.Store.resetExperiment();assert(BL.Store.state.enemy.hp===1&&BL.Store.state.enemy.atk===1&&Object.keys(BL.Store.state.enemy.traits).length===0,'experiment reset');
// comprehensive build reset must preserve progress/stats/unlocks
BL.Store.state.unlockedCards.v18_residue_cannon=true;BL.Store.state.claimedUnlocks.keep_me=true;BL.Store.state.stats.wins=12;BL.Store.state.character='combo';BL.Store.state.relics=['selection_lens'];BL.Store.state.enemy.hp=9;BL.Store.resetBuild();assert(BL.Store.state.character==='standard','build reset character');assert(JSON.stringify(BL.Store.state.deck)===JSON.stringify(D.DEFAULT_DECK),'build reset deck');assert(BL.Store.state.relics.length===0&&BL.Store.state.protocol===null,'build reset equips');assert(BL.Store.state.enemy.hp===1,'build reset enemy');assert(BL.Store.state.unlockedCards.v18_residue_cannon,'build reset erased unlock');assert(BL.Store.state.claimedUnlocks.keep_me,'build reset erased progress');assert(BL.Store.state.stats.wins===12,'build reset erased stats');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const id of ['buildResetHeaderBtn','buildResetBtn','deckClearBtn','deckResetBtn','relicResetBtn','protocolResetBtn','tuningResetBtn','conversionResetBtn','linkClearBtn','doctrineResetBtn','styleResetBtn','enemyTraitsClearBtn','enemyResetBtn'])assert(html.includes(`id="${id}"`),`reset UI missing ${id}`);assert(html.includes('全データ初期化'),'full data reset label missing');assert(html.includes('構成を全リセット'),'comprehensive build reset label missing');
console.log('PASS reset_controls.test.js');
