'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const mobile=fs.readFileSync(path.join(root,'js/ui/mobile.js'),'utf8');
const style=fs.readFileSync(path.join(root,'js/ui/styleView.js'),'utf8');
assert(html.includes('id="characterQuickPicker"'),'v0.77 quick picker markup missing');
assert(html.includes('js/ui/mobile.js?v=0.77.0'),'v0.77 mobile asset reference missing');
assert(mobile.includes('setupScrollTop'),'v0.76 mobile usability changes were lost');
assert(mobile.includes("BL.Battle?.start"),'v0.76 mobile normal battle fix was lost');
assert(style.includes('renderQuickPicker'),'v0.77 quick picker logic missing');
assert(style.includes('quickCharacterSelect')&&style.includes('quickStyleSelect'),'v0.77 quick selectors missing');
console.log('PASS v077_cumulative_ui.test.js');
