'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const versionJs=fs.readFileSync('js/version.js','utf8');
const state=fs.readFileSync('js/core/state.js','utf8');
assert(html.includes('id="buildVersionLabel"'),'visible version label target missing');
assert(html.includes('js/version.js?v=0.36.0'),'version source not loaded');
assert(!html.includes('PROTOTYPE 0.26'),'stale visible 0.26 remains');
assert(!html.includes('v0.32</title>'),'stale title version remains');
const label={textContent:''};
const ctx={window:{BuildLab:{}},document:{title:'',getElementById:id=>id==='buildVersionLabel'?label:null}};
vm.createContext(ctx);vm.runInContext(versionJs,ctx);
assert.equal(ctx.window.BuildLab.Version.label,'0.36');
assert.equal(ctx.window.BuildLab.Version.number,36);
assert.equal(ctx.window.BuildLab.Version.saveKey,'build_lab_proto_v36');
assert.equal(ctx.document.title,'BUILD LAB - ビルド実験場 v0.36');
assert.equal(label.textContent,'BUILD EXPERIMENT GAME / PROTOTYPE 0.36');
assert(state.includes("BL.Version?.saveKey||'build_lab_proto_v36'"),'state does not use central save version');
assert(state.includes("'build_lab_proto_v32'"),'v32 migration key missing');
console.log('PASS version_consistency.test.js');
