'use strict';
(function(){
  const BL=window.BuildLab,D=BL.Data; BL.UI=BL.UI||{};
  function availableConversions(s){return Object.entries(D.CARD_CONVERSIONS||{}).filter(([id,cv])=>!cv.requiresUnlock||!!s.unlockedConversions?.[id]);}
  function ensureTypeOptions(s){const sel=document.getElementById('conversionTypeFilter');if(!sel)return;const current=s.ui.conversionType||'all',allowed=availableConversions(s);sel.innerHTML='<option value="all">すべての役割変換</option>'+allowed.map(([id,cv])=>`<option value="${id}">${cv.name}</option>`).join('');sel.value=allowed.some(([id])=>id===current)?current:'all';if(sel.value!==current)s.ui.conversionType=sel.value;}
  function preview(cardId,convId){const c=D.CARDS[cardId],cv=D.CARD_CONVERSIONS[convId];if(!c||!cv)return'';const tags=D.getCardTags(BL.Store.state,cardId).join(' / ');return `<div class="conversion-preview"><strong>${cv.name}</strong>：${cv.desc}<br><small>変換後タグ：${tags}</small></div>`;}
  function renderConversions(){
    const s=BL.Store.state,area=document.getElementById('conversionPool'),summary=document.getElementById('conversionSelected');if(!area||!summary)return;
    const enabled=BL.Unlock.hasSystem(s,'card_conversion'),count=Object.keys(s.cardConversions||{}).length;summary.textContent=`${count}/2`;
    const search=document.getElementById('conversionSearch'),stateFilter=document.getElementById('conversionStateFilter'),typeFilter=document.getElementById('conversionTypeFilter');ensureTypeOptions(s);search.value=s.ui.conversionSearch||'';stateFilter.value=s.ui.conversionState||'deck';
    search.oninput=()=>{s.ui.conversionSearch=search.value;BL.Store.save();renderConversions();};stateFilter.onchange=()=>{s.ui.conversionState=stateFilter.value;BL.Store.save();renderConversions();};typeFilter.onchange=()=>{s.ui.conversionType=typeFilter.value;BL.Store.save();renderConversions();};
    if(!enabled){area.innerHTML='<div class="hint-box">カード役割変換は第2ボス撃破で解放されます。</div>';document.getElementById('conversionResultCount').textContent='未解放';return;}
    const q=(s.ui.conversionSearch||'').trim().toLowerCase(),allowed=new Map(availableConversions(s));
    let entries=Object.entries(D.CARDS).filter(([id,c])=>{if(!s.unlockedCards[id])return false;if(q&&!`${c.name} ${c.desc} ${c.tags.join(' ')} ${s.cardConversions[id]?D.CARD_CONVERSIONS[s.cardConversions[id]]?.name:''}`.toLowerCase().includes(q))return false;if(s.ui.conversionState==='deck'&&!s.deck.includes(id))return false;if(s.ui.conversionState==='converted'&&!s.cardConversions[id])return false;if(s.ui.conversionType!=='all'&&s.cardConversions[id]!==s.ui.conversionType)return false;return true;}).sort((a,b)=>a[1].name.localeCompare(b[1].name,'ja'));
    document.getElementById('conversionResultCount').textContent=`${entries.length}件`;area.innerHTML='';
    entries.forEach(([id,c])=>{const selected=s.cardConversions[id]||null,el=document.createElement('div');el.className='pool-card conversion-card'+(selected?' selected':'');const buttons=[`<button class="tune-btn ${!selected?'active':''}" data-conv="">解除</button>`];for(const [cid,cv] of allowed){const ok=D.canApplyConversion(id,cid);buttons.push(`<button class="tune-btn ${selected===cid?'active':''}" data-conv="${cid}" ${ok?'':'disabled'} title="${ok?cv.desc:'このカードには適用できません'}">${cv.name}</button>`);}el.innerHTML=`<div class="title">${c.name}</div><div class="desc">${c.desc}</div><div class="tags">${D.getCardTags(s,id).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="tuning-current">現在：${selected?D.CARD_CONVERSIONS[selected]?.name||'不明':'未変換'}</div>${selected?preview(id,selected):''}<div class="tuning-actions">${buttons.join('')}</div>`;el.querySelectorAll('[data-conv]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const cid=btn.dataset.conv;if(!cid){delete s.cardConversions[id];}else{if(!allowed.has(cid))return BL.UI.toast('この役割変換はまだ未解放です');if(!D.canApplyConversion(id,cid))return BL.UI.toast('このカードには適用できません');if(!s.cardConversions[id]&&Object.keys(s.cardConversions).length>=2)return BL.UI.toast('役割変換できるカード種類は最大2種類です');s.cardConversions[id]=cid;}BL.Store.save();BL.UI.renderAll();});area.appendChild(el);});
  }
  BL.UI.renderConversions=renderConversions;
})();
