'use strict';
(function(){
  const BL=window.BuildLab; BL.UI=BL.UI||{}; const D=BL.Data;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function matches(g,q,cat){if(cat!=='all'&&g.category!==cat)return false;if(!q)return true;const hay=[g.title,g.summary,g.category,g.where,g.unlock,g.example,...(g.points||[])].join(' ').toLowerCase();return hay.includes(q);}
  function renderCard(g){return `<article class="panel guide-card" id="guide-${esc(g.id)}"><div class="guide-card-head"><div><span class="guide-category">${esc(g.category)}</span><h3>${esc(g.title)}</h3><p class="guide-summary">${esc(g.summary)}</p></div><button class="ghost guide-jump" data-guide-open="${esc(g.id)}">開く</button></div><details class="guide-details"><summary>詳細を見る</summary><div class="guide-meta-grid"><div><b>設定・確認場所</b><span>${esc(g.where)}</span></div><div><b>解放</b><span>${esc(g.unlock)}</span></div></div><ul>${(g.points||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${g.example?`<div class="guide-example"><b>例</b><span>${esc(g.example)}</span></div>`:''}</details></article>`;}
  function fillCategories(){const sel=document.getElementById('guideCategoryFilter');if(!sel||sel.dataset.ready)return;sel.dataset.ready='1';for(const c of D.GUIDE_CATEGORIES||[]){const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o);}}
  function render(){const list=document.getElementById('guideList');if(!list)return;fillCategories();const q=(document.getElementById('guideSearch')?.value||'').trim().toLowerCase(),cat=document.getElementById('guideCategoryFilter')?.value||'all';const items=(D.SYSTEM_GUIDES||[]).filter(g=>matches(g,q,cat));list.innerHTML=items.map(renderCard).join('')||'<article class="panel empty-guide">条件に一致する解説がありません。</article>';const count=document.getElementById('guideResultCount');if(count)count.textContent=`${items.length}件`;const quick=document.getElementById('guideQuickLinks');if(quick)quick.innerHTML=items.map(g=>`<button type="button" class="guide-chip" data-guide-target="${esc(g.id)}">${esc(g.title)}</button>`).join('');list.querySelectorAll('[data-guide-open]').forEach(btn=>btn.onclick=()=>{const d=btn.closest('.guide-card')?.querySelector('details');if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'center'});}});document.querySelectorAll('[data-guide-target]').forEach(btn=>btn.onclick=()=>{const el=document.getElementById('guide-'+btn.dataset.guideTarget);if(!el)return;const d=el.querySelector('details');if(d)d.open=true;el.scrollIntoView({behavior:'smooth',block:'start'});});}
  function bind(){for(const id of ['guideSearch','guideCategoryFilter']){const el=document.getElementById(id);if(el&&!el.dataset.bound){el.dataset.bound='1';el.addEventListener(id==='guideSearch'?'input':'change',render);}}}
  BL.UI.renderGuides=function(){bind();render();};
})();
