'use strict';
const fs=require('fs'),path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){}};
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/<script src="([^"?]+)/g)){const f=m[1];if(f.includes('/ui/')||f.endsWith('app.js'))continue;require(path.join(root,f));}
const BL=BuildLab,D=BL.Data,E=D.ENDGAME58;
const alias={防御:['耐久','防御','反撃'],反撃:['反撃','耐久'],提示:['提示操作','提示','中央','左右'],連撃:['連撃'],敵行動:['敵行動','解析','出血'],出血:['出血','状態異常'],循環:['循環','捨て札','回収'],変質:['変質','二面'],二面:['二面','変質'],保持:['保持','提示操作'],記録:['記録'],自傷:['自傷','瀕死'],瀕死:['瀕死','自傷'],捨て札:['捨て札','循環'],状態異常:['状態異常','毒','火傷','出血','凍傷'],消失:['消失','復帰'],復帰:['復帰','消失','循環'],耐久:['耐久','防御'],回収:['回収','循環','捨て札'],錬成:['錬成','元素'],毒:['毒','状態異常'],火傷:['火傷','状態異常'],凍傷:['凍傷','状態異常'],役割変換:['役割変換','変換'],連結:['連結'],位置:['提示操作','中央','左右','位置'],調律:['調律'],変換:['役割変換','変換'],構築規格:['構築規格'],多タグ:['多タグ'],非選択:['非選択','捨て札'],予約:['予約','提示操作'],提示中:['提示中','提示操作'],元素:['元素'],ルーン:['ルーン'],アルカナ:['アルカナ']};
function words(xs){return [...new Set(xs.flatMap(x=>alias[x]||[x]))];}
function ctags(c){return [...(c.tags||[]),c.name||'',c.desc||''];}
function rawPower(c){let x=0;x+=(c.damage||0)*(c.hits||((c.damage!=null)?1:0));x+=(c.block||0)*.75;x+=(c.heal||0)*.7;if(c.status)x+=(c.status.amount||0)*2;if(c.statuses)x+=c.statuses.reduce((s,z)=>s+(z.amount||0)*1.5,0);if(c.perHitStatus)x+=(c.perHitStatus.amount||0)*(c.hits||1)*1.5;if(c.counter)x+=c.counter*8;if(c.fixedCounter)x+=c.fixedCounter*.6;if(c.effect)x+=3;if(c.vanishAfterUse)x+=1;return x;}
function cardScore(id,need,mode){const c=D.CARDS[id],txt=ctags(c).join(' ');let s=rawPower(c);for(const w of need)if(txt.includes(w))s+=mode==='concept'?10:7;if(c.deckable===false||c.directDeck===false||c.transformOnly)return-999;return s;}
function makeDeck(cid,st,trial,mode){const concepts=E.concepts(cid,st),need=words(mode==='trial'?trial.answers:mode==='concept'?concepts:[...concepts,...trial.answers]);const ids=Object.keys(D.CARDS).filter(id=>cardScore(id,need,mode)>-900).sort((a,b)=>cardScore(b,need,mode)-cardScore(a,need,mode));const deck=[];for(const id of ids){for(let k=0;k<2&&deck.length<10;k++)deck.push(id);if(deck.length===10)break;}return deck;}
const roleMap={'選択・提示':['提示','非選択','位置','保持'],'循環・復帰':['循環','消失','復帰','回収'],'症状運用':['状態異常','毒','火傷','出血','凍傷'],'HP履歴':['自傷','瀕死'],'接続履歴':['連結','記録'],'防御運用':['防御','耐久','反撃'],'役割変換':['役割変換','変換','変質'],'資源工程':['錬成','元素','ルーン','アルカナ'],'条件選択':['連撃','敵行動','構築規格']};
function supportScore(x,concepts,trial){const wants=[...concepts,...trial.answers];return (roleMap[x.v56Role]||[]).filter(a=>wants.includes(a)).length*10+(x.tags||[]).filter(t=>words(wants).includes(t)).length;}
function baseState(cid,st,trial,deck){const s=BL.Store.defaultState();for(const id of Object.keys(D.CARDS))s.unlockedCards[id]=true;for(const id of Object.keys(D.RELICS))s.unlockedRelics[id]=true;for(const id of Object.keys(D.PROTOCOLS))s.unlockedProtocols[id]=true;for(const id of Object.keys(D.TUNINGS))s.unlockedTunings[id]=true;for(const id of Object.keys(D.CARD_CONVERSIONS||{}))s.unlockedConversions[id]=true;for(const id of Object.keys(D.CHARACTERS))s.unlockedCharacters[id]=true;for(const id of Object.keys(D.CHARACTER_STYLES))s.unlockedCharacterStyles[id]=true;for(const id of Object.keys(D.TRAITS||{}))s.unlockedTraits[id]=true;for(const id of Object.keys(D.SYSTEMS||{}))s.unlockedSystems[id]=true;s.character=cid;if(st)s.characterStyles[cid]=st.id;s.deck=deck;s.enemy={...trial.enemy,traits:{...(trial.enemy.traits||{})}};const concepts=E.concepts(cid,st);s.relics=Object.entries(D.RELICS).sort((a,b)=>supportScore(b[1],concepts,trial)-supportScore(a[1],concepts,trial)).slice(0,3).map(x=>x[0]);s.protocol=Object.entries(D.PROTOCOLS).sort((a,b)=>supportScore(b[1],concepts,trial)-supportScore(a[1],concepts,trial))[0]?.[0]||null;const tunes=Object.entries(D.TUNINGS).sort((a,b)=>supportScore(b[1],concepts,trial)-supportScore(a[1],concepts,trial)).slice(0,2).map(x=>x[0]);s.cardTunings={};deck.slice(0,2).forEach((id,i)=>s.cardTunings[id]=tunes[i]);return s;}
function seedRandom(seed){let x=seed>>>0;return()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296;};}
function chooseIndex(b,trial,concepts){let best=0,bs=-1e9;for(let i=0;i<b.prompt.length;i++){const inst=b.prompt[i],c=D.CARDS[inst.transformedCardId||inst.cardId]||D.CARDS[inst.cardId],txt=ctags(c).join(' ');let s=rawPower(c);for(const w of words([...concepts,...trial.answers]))if(txt.includes(w))s+=4;if(b.player.hp<=b.player.maxHp*.45)s+=(c.block||0)*1.2+(c.heal||0)*2;if(b.enemy.hp<=b.enemy.maxHp*.3)s+=(c.damage||0)*(c.hits||1)*.8;if(c.onDiscard)s-=2;if(s>bs){bs=s;best=i;}}return best;}
function runOne(cid,st,trial,deck,seed){const old=Math.random;Math.random=seedRandom(seed);let result=null;try{BL.Store.state=baseState(cid,st,trial,deck);BL.Battle.onEnd=r=>result=r;const r=BL.Battle.create(false);if(r.error)return{win:false,error:r.error,turn:0};let guard=0;const concepts=E.concepts(cid,st);while(BL.Battle.current&&guard++<70){const b=BL.Battle.current;if(!b.prompt.length){BL.Battle.retire();break;}BL.Battle.play(chooseIndex(b,trial,concepts));}if(BL.Battle.current)BL.Battle.retire();const bb=result?.battle;return{win:!!result?.win,turn:bb?.turn||guard,used:bb?.events?.recent?.filter(e=>e.type==='used').map(e=>e.cardId)||[]};}finally{Math.random=old;BL.Battle.onEnd=null;if(BL.Battle.current)BL.Battle.retire();}}
const variants=[];for(const [cid,c] of Object.entries(D.CHARACTERS)){variants.push({cid,st:null,name:c.name+'・原型'});for(const st of Object.values(D.CHARACTER_STYLES).filter(x=>x.character===cid))variants.push({cid,st,name:c.name+'・'+st.name});}
const shard=Number(process.env.SHARD||0),shards=Number(process.env.SHARDS||1),seedOffset=Number(process.env.SEED_OFFSET||0),allVariants=variants.slice();const indexed=allVariants.map((v,i)=>({...v,_globalIndex:i}));variants.splice(0,variants.length,...indexed.filter(v=>v._globalIndex%shards===shard));
const results=[],cardUse={},relicUse={},protocolUse={},statusWins={poison:0,burn:0,bleed:0,frost:0};let battles=0,wins=0;
for(let vi=0;vi<variants.length;vi++){const v=variants[vi];for(const trial of Object.values(E.trials)){let best=null;for(const mode of ['hybrid','trial','concept']){const deck=makeDeck(v.cid,v.st,trial,mode);let w=0,turns=0;for(let k=0;k<1;k++){const r=runOne(v.cid,v.st,trial,deck,610000+seedOffset+v._globalIndex*100+Object.keys(E.trials).indexOf(trial.id)*10+k);battles++;if(r.win){w++;wins++;}turns+=r.turn;}const rec={mode,wins:w,runs:1,rate:w,turns:turns/2,deck};if(!best||rec.rate>best.rate||(rec.rate===best.rate&&rec.turns<best.turns))best=rec;}results.push({variant:v.name,cid:v.cid,style:v.st?.id||null,trial:trial.id,...best});if(best.rate>0){for(const id of new Set(best.deck))cardUse[id]=(cardUse[id]||0)+1;const s=baseState(v.cid,v.st,trial,best.deck);for(const id of s.relics)relicUse[id]=(relicUse[id]||0)+1;if(s.protocol)protocolUse[s.protocol]=(protocolUse[s.protocol]||0)+1;for(const [key,needle] of Object.entries({poison:'毒',burn:'火傷',bleed:'出血',frost:'凍傷'}))if(best.deck.some(id=>ctags(D.CARDS[id]).join(' ').includes(needle)))statusWins[key]++;}}
 if((vi+1)%20===0)console.error('variants',vi+1,'/',variants.length);
}
const byVariant={};for(const r of results){const a=byVariant[r.variant]||(byVariant[r.variant]={trials:0,won:0,conceptWon:0});a.trials++;if(r.rate>0)a.won++;const cs=E.concepts(r.cid,r.style?D.CHARACTER_STYLES[r.style]:null);if(r.rate>0&&E.trials[r.trial].answers.some(x=>cs.includes(x)))a.conceptWon++;}
const byTrial={};for(const t of Object.values(E.trials))byTrial[t.id]={name:t.name,total:0,won:0,avgRate:0};for(const r of results){const x=byTrial[r.trial];x.total++;if(r.rate>0)x.won++;x.avgRate+=r.rate;}for(const x of Object.values(byTrial))x.avgRate/=x.total;
const summary={version:'0.61-combat-audit',generatedAt:new Date().toISOString(),variants:variants.length,trials:Object.keys(E.trials).length,battles,wins,coverage:{variantsWithAnyWin:Object.values(byVariant).filter(x=>x.won>0).length,variantsWithConceptWin:Object.values(byVariant).filter(x=>x.conceptWon>0).length,variantsAllTrials:Object.values(byVariant).filter(x=>x.won===8).length},byTrial,statusWins,zeroUseCards:Object.keys(D.CARDS).filter(id=>!cardUse[id]).length,topCards:Object.entries(cardUse).sort((a,b)=>b[1]-a[1]).slice(0,25),topRelics:Object.entries(relicUse).sort((a,b)=>b[1]-a[1]).slice(0,15),topProtocols:Object.entries(protocolUse).sort((a,b)=>b[1]-a[1]).slice(0,15),failedVariants:Object.entries(byVariant).filter(([_,x])=>x.won===0).map(([name,x])=>({name,...x})),weakConceptVariants:Object.entries(byVariant).filter(([_,x])=>x.conceptWon===0).map(([name,x])=>({name,...x}))};
fs.writeFileSync(path.join(root,`AUDIT_v0.61_REAL_COMBAT_SHARD${shard}.json`),JSON.stringify({summary,results},null,2));console.log(JSON.stringify(summary,null,2));
